# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WA7_Chatterjee_5185' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WA7_Chatterjee_5185
  pod 'Alamofire'

  target 'WA7_Chatterjee_5185Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WA7_Chatterjee_5185UITests' do
    # Pods for testing
  end

end
