# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WA6_Chatterjee_5185' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WA6_Chatterjee_5185

  pod 'Alamofire'

end
